version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  collector:
    build:
      context: .
      dockerfile: ./services/collector/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - STREAM_NAME=logs
      - MAX_MESSAGE_BYTES=65536
      - TRIM_MAXLEN=50000
      - CORS_ALLOW_ORIGINS=http://localhost:8080
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:8081/healthz')"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    ports:
      - "8081:8081"

  distributor:
    build:
      context: .
      dockerfile: ./services/distributor/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - STREAM_NAME=logs
      - CONSUMER_GROUP=distributors
      - CONSUMER_NAME=dist-1
      - PENDING_IDLE_MS=60000
      - BATCH_COUNT=128
      - BLOCK_MS=2000
      - SUBSCRIBER_QUEUE_LEN=1000
      - ANALYZERS=[{"name":"an1","weight":2},{"name":"an2","weight":1}]
      - CORS_ALLOW_ORIGINS=http://localhost:8080
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:8082/healthz')"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    ports:
      - "8082:8082"

  distributor2:
    build:
      context: .
      dockerfile: ./services/distributor/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - STREAM_NAME=logs
      - CONSUMER_GROUP=distributors
      - CONSUMER_NAME=dist-2
      - PENDING_IDLE_MS=60000
      - BATCH_COUNT=128
      - BLOCK_MS=2000
      - SUBSCRIBER_QUEUE_LEN=1000
      - ANALYZERS=[{"name":"an1","weight":2},{"name":"an2","weight":1}]
      - CORS_ALLOW_ORIGINS=http://localhost:8080
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:8082/healthz')"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s

  ui:
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile
    restart: unless-stopped
    environment:
      - DISTRIBUTOR_HTTP=http://localhost:8082
    depends_on:
      - distributor
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/ >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    ports:
      - "8080:8080"

  analyzer1:
    build:
      context: .
      dockerfile: ./services/analyzer/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - ANALYZER_NAME=an1
      - ANALYZER_GROUP=analyzers
      - CONSUMER_NAME=an1-c1
      - BATCH_COUNT=256
      - BLOCK_MS=2000
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:8090/healthz')"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    ports:
      - "8091:8090"

  analyzer2:
    build:
      context: .
      dockerfile: ./services/analyzer/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379/0
      - ANALYZER_NAME=an2
      - ANALYZER_GROUP=analyzers
      - CONSUMER_NAME=an2-c1
      - BATCH_COUNT=256
      - BLOCK_MS=2000
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://localhost:8090/healthz')"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
    ports:
      - "8092:8090"

volumes:
  redis-data:

